$schema: https://json-schema.org/draft/2020-12/schema
description: Manipulates dates and times by addition or subtraction
type: object
properties:
  date:
    anyOf:
    - $ref: bblocks://ogc.openeo.types.date-time
    - $ref: bblocks://ogc.openeo.types.date
  value:
    type: integer
  unit:
    type: string
    enum:
    - millisecond
    - second
    - minute
    - hour
    - day
    - week
    - month
    - year
required:
- date
- value
- unit
