$schema: https://json-schema.org/draft/2020-12/schema
description: Compute anomalies
type: object
properties:
  data:
    $ref: bblocks://ogc.openeo.types.datacube
  normals:
    $ref: bblocks://ogc.openeo.types.datacube
  period:
    type: string
    enum:
    - hour
    - day
    - week
    - dekad
    - month
    - season
    - tropical-season
    - year
    - decade
    - decade-ad
    - climatology-period
    - single-period
required:
- data
- normals
- period
