$schema: https://json-schema.org/draft/2020-12/schema
type: array
subtype: temporal-intervals
title: Multiple temporal intervals
description: Left-closed temporal intervals, which are allowed to overlap. Formatted as an
  array of two-element arrays, each being an array with subtype `temporal-interval`.
items:
  $ref: bblocks://ogc.openeo.types.temporal-interval
minItems: 1
