$schema: https://json-schema.org/draft/2020-12/schema
description: Clip a value between a minimum and a maximum
type: object
properties:
  x:
    type:
    - number
    - 'null'
  min:
    type: number
  max:
    type: number
required:
- x
- min
- max
