$schema: https://json-schema.org/draft/2020-12/schema
description: Minimum value
type: object
properties:
  data:
    type: array
    items:
      type:
      - number
      - 'null'
  ignore_nodata:
    type: boolean
required:
- data
