$schema: https://json-schema.org/draft/2020-12/schema
description: Resample temporal dimensions to match a target data cube
type: object
properties:
  data:
    $ref: bblocks://ogc.openeo.types.datacube
  target:
    $ref: bblocks://ogc.openeo.types.datacube
  dimension:
    type:
    - string
    - 'null'
  valid_within:
    type:
    - number
    - 'null'
required:
- data
- target
