$schema: https://json-schema.org/draft/2020-12/schema
description: Apply a process to pixels in a n-dimensional neighborhood
type: object
properties:
  data:
    $ref: bblocks://ogc.openeo.types.datacube
  process:
    $ref: bblocks://ogc.openeo.types.process-graph
  size:
    type: array
    items:
      $ref: bblocks://ogc.openeo.types.chunk-size
  overlap:
    anyOf:
    - title: Without overlap
      type: 'null'
    - title: With overlap
      type: array
      items:
        $ref: bblocks://ogc.openeo.types.chunk-size
  context:
    description: Any data type.
required:
- data
- process
- size
