$schema: https://json-schema.org/draft/2020-12/schema
description: Filter an array based on a condition
type: object
properties:
  data:
    type: array
    items:
      description: Any data type is allowed.
  condition:
    $ref: bblocks://ogc.openeo.types.process-graph
  context:
    description: Any data type.
required:
- data
- condition
