$schema: https://json-schema.org/draft/2020-12/schema
description: Resample the spatial dimensions to match a target data cube
type: object
properties:
  data:
    $ref: bblocks://ogc.openeo.types.datacube
  target:
    $ref: bblocks://ogc.openeo.types.datacube
  method:
    type: string
    enum:
    - average
    - bilinear
    - cubic
    - cubicspline
    - lanczos
    - max
    - med
    - min
    - mode
    - near
    - q1
    - q3
    - rms
    - sum
required:
- data
- target
