$schema: https://json-schema.org/draft/2020-12/schema
description: Remove dimension labels with no-data values
type: object
properties:
  data:
    $ref: bblocks://ogc.openeo.types.datacube
required:
- data
