$schema: https://json-schema.org/draft/2020-12/schema
description: Compute climatology normals
type: object
properties:
  data:
    $ref: bblocks://ogc.openeo.types.datacube
  period:
    type: string
    enum:
    - day
    - month
    - season
    - tropical-season
    - climatology-period
  climatology_period:
    type: array
    uniqueItems: true
    minItems: 2
    maxItems: 2
    items:
      $ref: bblocks://ogc.openeo.types.year
required:
- data
- period
